/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package views;

import controller.Autenticacion;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class AutenticacionViews extends javax.swing.JDialog {

    /**
     * Creates new form Autenticacion
     */
    public AutenticacionViews(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton34 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        buttonEnter = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jButton18 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtnroCuenta = new javax.swing.JTextField();
        txtpin = new javax.swing.JTextField();
        jButtoningresar = new javax.swing.JButton();
        txtnrocuenta = new javax.swing.JTextField();
        txtpiningresado = new javax.swing.JTextField();

        jButton34.setBackground(new java.awt.Color(153, 153, 153));
        jButton34.setForeground(new java.awt.Color(0, 0, 0));
        jButton34.setText("9");
        jButton34.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 0)));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(null);

        jPanel7.setBackground(new java.awt.Color(102, 102, 102));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.setLayout(null);

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("2");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 0)));
        jPanel7.add(jButton1);
        jButton1.setBounds(129, 26, 99, 44);

        jButton2.setBackground(new java.awt.Color(153, 153, 153));
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("3");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 0)));
        jPanel7.add(jButton2);
        jButton2.setBounds(240, 26, 99, 44);

        jButton3.setBackground(new java.awt.Color(153, 153, 153));
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("5");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 0)));
        jPanel7.add(jButton3);
        jButton3.setBounds(129, 91, 99, 44);

        jButton4.setBackground(new java.awt.Color(153, 153, 153));
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setText("1");
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 0)));
        jPanel7.add(jButton4);
        jButton4.setBounds(18, 26, 99, 44);

        jButton5.setBackground(new java.awt.Color(153, 153, 153));
        jButton5.setForeground(new java.awt.Color(0, 0, 0));
        jButton5.setText("6");
        jButton5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 0)));
        jPanel7.add(jButton5);
        jButton5.setBounds(240, 91, 99, 44);

        jButton6.setBackground(new java.awt.Color(153, 153, 153));
        jButton6.setForeground(new java.awt.Color(0, 0, 0));
        jButton6.setText("7");
        jButton6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 0)));
        jPanel7.add(jButton6);
        jButton6.setBounds(18, 157, 99, 44);

        jButton8.setBackground(new java.awt.Color(153, 153, 153));
        jButton8.setForeground(new java.awt.Color(0, 0, 0));
        jButton8.setText("8");
        jButton8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 0)));
        jPanel7.add(jButton8);
        jButton8.setBounds(129, 157, 99, 44);

        jButton10.setBackground(new java.awt.Color(153, 153, 153));
        jButton10.setForeground(new java.awt.Color(0, 0, 0));
        jButton10.setText("4");
        jButton10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 0)));
        jPanel7.add(jButton10);
        jButton10.setBounds(18, 91, 99, 44);

        jButton11.setBackground(new java.awt.Color(153, 153, 153));
        jButton11.setForeground(new java.awt.Color(0, 0, 0));
        jButton11.setText(".");
        jButton11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 0)));
        jPanel7.add(jButton11);
        jButton11.setBounds(129, 222, 99, 44);

        jButton12.setBackground(new java.awt.Color(255, 255, 0));
        jButton12.setForeground(new java.awt.Color(0, 0, 0));
        jButton12.setText("CLEAR");
        jButton12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 102)));
        jPanel7.add(jButton12);
        jButton12.setBounds(428, 126, 99, 55);

        buttonEnter.setBackground(new java.awt.Color(0, 204, 0));
        buttonEnter.setForeground(new java.awt.Color(0, 0, 0));
        buttonEnter.setText("ENTER");
        buttonEnter.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 51)));
        buttonEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEnterActionPerformed(evt);
            }
        });
        jPanel7.add(buttonEnter);
        buttonEnter.setBounds(430, 210, 99, 55);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 316, Short.MAX_VALUE)
        );

        jPanel7.add(jPanel8);
        jPanel8.setBounds(367, 8, 10, 316);

        jButton18.setBackground(new java.awt.Color(255, 0, 0));
        jButton18.setForeground(new java.awt.Color(0, 0, 0));
        jButton18.setText("CANCEL");
        jButton18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 255)));
        jPanel7.add(jButton18);
        jButton18.setBounds(430, 40, 99, 55);

        jButton33.setBackground(new java.awt.Color(153, 153, 153));
        jButton33.setForeground(new java.awt.Color(0, 0, 0));
        jButton33.setText("9");
        jButton33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 0)));
        jPanel7.add(jButton33);
        jButton33.setBounds(240, 157, 99, 44);

        jButton13.setBackground(new java.awt.Color(153, 153, 153));
        jButton13.setForeground(new java.awt.Color(0, 0, 0));
        jButton13.setText("0");
        jButton13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 0)));
        jPanel7.add(jButton13);
        jButton13.setBounds(18, 222, 99, 44);

        jButton15.setBackground(new java.awt.Color(153, 153, 153));
        jButton15.setForeground(new java.awt.Color(0, 0, 0));
        jButton15.setText("00");
        jButton15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 0)));
        jPanel7.add(jButton15);
        jButton15.setBounds(240, 222, 99, 44);

        jPanel2.add(jPanel7);
        jPanel7.setBounds(6, 6, 0, 0);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(6, 369, 0, 0);

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CajeroAutomatico");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.add(jPanel4);
        jPanel4.setBounds(6, 6, 682, 85);

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setLayout(null);

        jPanel6.setBackground(new java.awt.Color(0, 255, 204));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Numero de cuenta:");
        jPanel6.add(jLabel2);
        jLabel2.setBounds(8, 8, 160, 25);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel6.add(jLabel3);
        jLabel3.setBounds(170, 8, 404, 0);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("PIN:");
        jPanel6.add(jLabel4);
        jLabel4.setBounds(8, 40, 80, 25);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jPanel6.add(jLabel5);
        jLabel5.setBounds(47, 40, 533, 0);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jPanel6.add(jLabel6);
        jLabel6.setBounds(8, 72, 0, 0);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jPanel6.add(jLabel7);
        jLabel7.setBounds(53, 72, 0, 0);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jPanel6.add(jLabel8);
        jLabel8.setBounds(59, 72, 0, 0);

        txtnroCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnroCuentaActionPerformed(evt);
            }
        });
        jPanel6.add(txtnroCuenta);
        txtnroCuenta.setBounds(170, 12, 271, 26);
        jPanel6.add(txtpin);
        txtpin.setBounds(170, 40, 270, 26);

        jPanel5.add(jPanel6);
        jPanel6.setBounds(40, 10, 540, 232);

        jPanel3.add(jPanel5);
        jPanel5.setBounds(44, 90, 610, 248);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(6, 6, 694, 0);

        jButtoningresar.setText("ingresar");
        jButtoningresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoningresarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtoningresar);
        jButtoningresar.setBounds(100, 350, 75, 27);

        txtnrocuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnrocuentaActionPerformed(evt);
            }
        });
        getContentPane().add(txtnrocuenta);
        txtnrocuenta.setBounds(40, 40, 370, 26);
        getContentPane().add(txtpiningresado);
        txtpiningresado.setBounds(50, 200, 370, 26);

        setSize(new java.awt.Dimension(576, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtnroCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnroCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnroCuentaActionPerformed

    private void buttonEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEnterActionPerformed

    }//GEN-LAST:event_buttonEnterActionPerformed

    private void jButtoningresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoningresarActionPerformed
        Autenticacion a = new Autenticacion();
        String[] usuarioAutenticado = a.autenticar(txtnrocuenta.getText(), txtpiningresado.getText());
        if (usuarioAutenticado != null) {
            InterfazPrincipal interfaz =  new InterfazPrincipal(usuarioAutenticado);
            interfaz.setVisible(true);
            dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Número de cuenta o PIN incorrectos", "Error", JOptionPane.ERROR_MESSAGE);
            txtnrocuenta.setText("");
            txtpiningresado.setText("");
        }
    }//GEN-LAST:event_jButtoningresarActionPerformed

    private void txtnrocuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnrocuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnrocuentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AutenticacionViews.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AutenticacionViews.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AutenticacionViews.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AutenticacionViews.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AutenticacionViews dialog = new AutenticacionViews(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonEnter;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButtoningresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTextField txtnroCuenta;
    private javax.swing.JTextField txtnrocuenta;
    private javax.swing.JTextField txtpin;
    private javax.swing.JTextField txtpiningresado;
    // End of variables declaration//GEN-END:variables
}
